### ISSUE TITLE
Port improvements from test-gen-support to master

### ISSUE THREAD

**Issue by tautschnig** [diffblue/cbmc#1121]
I'm mainly opening this issue to understand whether this is any plan or strategy to do this, or whether this isn't even planned at all. It seems test-gen-support has a large array of improvements in the Java front-end that do not appear to be particularly specific to test generation.

**Comment by tautschnig** [comment]
Here's a task list, in chronological order, with commit series to be read from top to bottom:

- d47d503b6 Get symbol of member expression
- 27153d142 Auxiliary function to check if the ssa has enough data to build an identifier
- 298740647 Bitwise operators for mpinteger
- d81dd759c Auxiliary function to retrieve tail of trace and added dead command to trace
- 7fb817448 Fix arithmetic shift operators
- fb616c542 Added a new class for handling the internals
- fc756f336 Adding more symbols that should be excluded
- 2f5b86689 Autocomplete script for bash
- 0cf34af4d Support for Java assume
- 1436e3960 Regression tests for Java assume
- 5c309076a Remove assume as coverage target
- e55f20b6f output covered lines as CSV in show_properties
- 2ae1f47f3 compress list of lines into line ranges
- f5f47a704 add regression test for coverage lines
- 02d2b9d0c fix problem with missing comma / range fix for reaching end
- b7d828bc1 Updated dump-C to use the new class
- [ ] Migrate #579 (8ae50cd8c)
- fef1fed6b update interpreter
- [ ] Migrate #580 (60744ee17)
- 1aede785e Preprocessing of goto programs for string refinement
- 3a2e210d4 Moving is_java_string_type functions to string_preprocess
- 70af9ce61 Moving refined_string_type to util
- 2929d7f04 Removed distinction between c string type and refined string type
- 5cb0e5e09 Removed mention of c string type
- [ ] Migrate #669 (e81a5e04e)
- 72ad6ad81 Making add_string_type more generic
- c9ff379f1 new identifier for converting char pointer to array
- a04dc21fc Many corrections in preprocessing of strings
- bdbeaf586 Many corrections in string refinement
- 6958a561d Need to assign length before calls since it can be overwritten by functions with side-effect
- [ ] Migrate #675 (e4e26d861)
- df36fecde const refs and clean up
- [ ] Migrate #688 (a11a70b53)
- 6cc1266de Adding refined_string_type to util Makefile
- 402f8e180 Adding string preprocessing of goto-programs to Makefile
- 055829123 Adding string solver cpp files to Makefile
- c7328e225 Adding the string refinement option to the CBMC solvers
- 9d2a1158d Change option name to --refine-strings
- [ ] Migrate #676 (3eeb73d60)
- c7691a4ff Restructuration of tests on strings
- [ ] Migrate #678 (c3cc87261)
- 2e62c6638 New class for sparse vectors in util
- 5d2919b36 Interpreter: switch to sparse vector memory map
- 1b97f3dbc Add support for unbounded-size objects
- [ ] Migrate #689 (28fb701b5)
- 072e37412 Display dynamic object names as 'data' in JSON traces
- [ ] Migrate #717 (2499213a3)
- a5f773923 set internal for specific variables in the counterexample trace for test-gen-support
- 508131009 added internal field to json output
- [ ] Migrate #709 (932d7df71)
- 9ddfb302a Add includes to sparse_vector.h
- [ ] Migrate #742 (6b5d9b70a)
- da849ee28 Adding conversion for functions of the Java Character library
- dead0224b Corrected type problem for the function Character.forDigit:(II)C
- [ ] Migrate #699 (03891c93a)
- 6c1f70074 Adding options to cbmc for parameters of the string solver
- d5c6ac636 Added option to the string solver for string length and printability
- 91d07b1e1 Bug corrections in string refinement
- [ ] Migrate #738 (8081a9a29)
- 4c4d85ca6 Implement function-only coverage
- 161aeee31 Apply review comments to coverage code
- [ ] Migrate #758 (372bafbd1)
- 46151843e Restore array skip-initialize flag
- [ ] Migrate #789 (051a245b3)
- 7e1b38208 Set function member for class identifier assignment
- [ ] Migrate #794 (788a60e45)
- 3cb035e4d Fix style to silence cpplint
- [ ] Migrate #799 (cb065bfbf)
- 44041aeff Allowing some options for string refinement
- [ ] Migrate #790 (4bebee959)
- 2fc6f099d Preserve true array type in Java -> GOTO conversion. Fixes #184.
- [ ] Migrate #788 (75337a21e)
- 318ab8612 Improve `class_typet`'s base description
- 668f30f0e Always convert methods in two phases, even in eager mode
- 85b1e4f4f Invoke static initializers on demand
- c63141902 Add tests for static initialization order
- [ ] Migrate #796 (b04878720)
- 5851f6374 Order string functions in alphabetical order
- [ ] Migrate #800 (e05353e49)
- 03667afea Make add_axioms_from_bool add concret constraints
- aaa56bb21 Adding tests for issue diffblue/test-gen#119
- 621f366ff Correct a mistake in the signature for String.valueOf
- [ ] Migrate #802 (72e3e350d)
- 02f86978d Adding overflow checks in the parsing of integer (#172)
- [ ] Migrate #805 (cc3e3cc61)
- f0004a5d2 Corrections on generated axioms
- 94e9c647e Various improvements in string refinement
- [ ] Migrate #806 (57f592745)
- 718683f6f Remove trace_stackt
- [ ] Migrate #813 (fcafa4178)
- 035ae9211 Restore array-set for nondet arrays
- [ ] Migrate #820 (935825efc)
- 083d8a65f Always report exceptinal output in __CPROVER_start
- [ ] Migrate #814 (2f5a39156)
- 3c5ae1a56 Allow checkcast of null pointer
- [ ] Migrate #821 (e81b1d9fe)
- 77ac3a243 Fix Java object factory recursion set
- [ ] Migrate #824 (58f3c446c)
- 241dbee16 Add org.cprover package and makefile
- f85494b07 Add remove_java_nondet
- 19c8d8d7c Suppress loading methods with nondet signatures
- dc94557d8 Rearrange loop in remove_java_nondet
- f4a47f9e1 Split java nondet pass in two
- ff72ddc8c Ensure assume only throws upon predicate failure
- [ ] Migrate #691 (3fddf20d3)
- 8ad72a70d Fix linter complaint
- [ ] Migrate #866 (f5aa61270)
- c195e63c3 Remove 'erase' in replace_java_nondet.cpp
- 6deaa3b89 Remove skip in replace_java_nondet.cpp
- d15d84238 Fix indentation in convert_nondet
- [ ] Migrate #860 (d11747558)
- 520cf38ce Handle typecast when evaluating addresses in the interpreter
- [ ] Migrate #854 (468ad17b6)
- b8586a6e3 Move coverage arg-parsing into cover.cpp
- [ ] Migrate #857 (30b5c726f)
- 21eeb2979 Enable working smoke tests
- 7cf1c92d4 Fixes in pre-processing for issue #170
- [ ] Migrate #822 (64c8bdf70)
- 6b24ec76d Implement StringBuffer methods
- [ ] Migrate #843 (6c626c7c1)
- 2c78d4648 Correcting constraints for conversion from int diffblue/test-gen#241
- [ ] Migrate #840 (0bc3416d3)
- 95844654f Correction in add_axioms_for_set_length
- [ ] Migrate #841 (aa78fc1f8)
- 072ed0f8b Overhaul of string concretization
- [ ] Migrate #819 (f8f761092)
- 0e5a54e97 Avoid initializing the index set if not needed diffblue/test-gen#199
- [ ] Migrate #844 (fe03a6e9e)
- df1caca1e Adding namespace to arguments of from_expr in debug diffblue/test-gen#201
- [ ] Migrate #829 (34a847c76)
- 6d1feea66 Set the bytecode index for the instrumentation in goto_check.cpp
- 67961355a Added the bytecode index to the expected result of the regression tests
- [ ] Migrate #848 (2dc8cf3c3)
- 1e9123f0a Always initialise the exceptional return variable of the entry function
- [ ] Migrate #856 (c5033663f)
- 43e324f39 Added new friend to bmc to handle refactoring
- [ ] Migrate #901 (f22a696f9)
- f4ba652cc Fix signed/unsigned comparison warning
- [ ] Migrate #938 (05d1ec641)
- 539db2549 Fix use-after-free bugs
- [ ] Migrate #939 (f791fef65)
- 013f442fc Add missing swap instruction
- [ ] Migrate #942 (be3f76179)
- 851037459 Revert "Remove variable that is always false"
- [ ] Migrate #941 (a54d806fb)
- eff658a97 Add hanlded for constant strings
- 06837c8bf Use the member functions to make code more robust
- 575b34331 Adding simple test for trace correctness
- [ ] Migrate #958 (927e48c8e)
- b6e193ea3 Adding accessors for the access properties
- [ ] Migrate #975 (d0ec24270)
- d4378331e Added an uncaught exceptions analysis
- 047671b09 add the uncaught exceptions analysis to the Makefile
- ca693b4de Make sure that both the caller and callee have exceptional return vars before instrumenting function calls
- 47cd9273e Ignore AssertionError This is ignored when we comoute the set of escaped exceptions as well as when replacing throws.
- 229817d23 Remove duplicate version of class_hierarchyt::get_children_trans_rec
- f42cc33e4 Addressed reviewers comments
- [ ] Migrate #940 (c07cdf953)
- 37c0a366a Avoid marking main function call / arguments as internal
- [ ] Migrate #960 (671193c2f)
- befb6e261 Fix a mistake in java_identifier_start
- [ ] Migrate #943 (0bbfffd96)
- 8f120bd7a Declaring auxiliary function for allocation of dynamic objects
- af2fd46c7 Replacement of string preprocessing for Java
- 45a026040 Merging string and character preprocess as one argument of bytecode conversion
- 7653a764b Removing and deactivating the old preprocessing
- [ ] Migrate #906 (5b5a4d223)
- b2dd3a21b Disallow null pointer in data field of String
- [ ] Migrate #900 (00bb9b1c2)
- 116237769 Specification for contains in the case of a constant argument diffblue/test-gen#159
- [ ] Migrate #828 (12c5f2661)
- e3b44c700 Avoid copies of string preprocess objects
- 0cc5ae662 Using delete to forbid copies of objects
- [ ] Migrate #980 (f05ea1748)
- 86de08fbc Update strings-smoke-test
- 56800d52e Add strings-smoke-tests to regression Makefile
- [ ] Migrate #976 (f4f4c44c7)
- eb9a78974 Correcting addition of symbol to symbol map
- [ ] Migrate #837 (ac71afe93)
- 0dcb77341 Change the step at which we replace String methods code
- ca32a0a1d Removing string conversion from method conversion
- dcf7614d4 Correcting replace_string_methods to not overwrite the map we iterate on
- 65f2e3696 Overwrite String type
- [ ] Migrate #983 (ff81171bb)
- f9199a097 Make index_of precise diffblue/test-gen#77
- bc59d0c6a Making lastIndexOf precise diffblue/test-gen#77
- 4f4df8e1a Optimize last_index_of for constant argument
- 9b11653a8 Updating comments for index_of and last_index_of on characters
- bc3eedc52 Replacing str and substring by haystack and needle
- 666bec088 Removing comments about lastIndexOf being imprecise
- 1eb3263f1 Making comments about the output more precise
- 68cdc6fd1 Renaming str and substring to haystack and needle
- 2d16c2cf9 Correct comments and axioms in lastIndexOf
- f3f5a19b2 Replacing str and substring by haystack and needle in the comments
- a4ab7db7b Updating comments for functions adding axioms for index_of
- 1eb7d748e Uniformising mathematical notations in comments
- 069da5161 Typo in comment
- 7edfe0d2d Typo in comment
- 3e9668a71 Correcting a mistake, universal variable was used in non-quantified formula
- b06476c47 Correcting indentation in the comments
- af98378f8 Correcting misuse of univ variable qvar instead of qvar2
- 80dff96f9 Correcting lower bound in axiom added for last_index_of
- d4a9b2a5b More comments on the output of last_index_of functions
- 94f99b5d5 Adding forgotten precondition in not_contains constraint
- cf5b5d374 Update regressions tests for indexOf and lastIndexOf
- [ ] Migrate #978 (2120a44b9)
- 7dc5efa6f Adding a mode option to json output diffblue/test-gen#294
- d41448fb1 Call to lookup that does not throw when symbol is not found
- 62d355cc7 Use the from_type function to get string for the type
- fd80fe6be Adding assertion to make sure "type" field is always set
- b0b8bbccc Adding assertions to prevent the "data" field from not being set
- 2c27b416b Assertion to forbid calling json() with nil values
- [ ] Migrate #889 (d475cf139)
- c61d0951a Improve constructor and copy of strings
- [ ] Migrate #993 (07001e996)
- 985baf18a Take care of cases where the symbol exists in table diffblue/test-gen#480
- 9936ddbdb Improvements following review on PR#995
- [ ] Migrate #995 (4b9f42ecf)
- 770728742 Always push the current exceptional return variable on the stack before converting an exception handler
- bb9c28ac6 Added regression test capturing an exception handler that does not start with astore
- 8f629b6a0 Addressed reviewers comments
- [ ] Migrate #996 (a308fb5e2)
- 72b611a1b Improvements on lengths
- 161329004 Update smoke tests for String.length
- [ ] Migrate #994 (2105ee9dc)
- 01e9e6791 Using unique pointers to avoid memory leak in json for expressions
- [ ] Migrate #1006 (3d80c6f8c)
- e9e3989bf Providing code for Object.getClass() in bytecode conversion
- db1cd5f34 Cleaning the initialization of string expressions from constants
- [ ] Migrate #945 (1a3eb1ceb)
- 4324bbd96 Disable warnings that result from array-of with zero length
- [ ] Migrate #1012 (23e2c9b2c)
- e1aadeb44 Write traces to status() not cout
- [ ] Migrate #1003 (38907fce4)
- 0ee493340 Add simple time limiting to prop_conv and propt
- [ ] Migrate #1004 (c50f3d595)
- 7cf8d5f58 Add support for recording and propagating class access flags
- [ ] Migrate #1000 (6fa72c839)
- f88f46177 Remove stray include accidentally merged from master
- [ ] Migrate #1014 (2d9739300)
- 4701c0b32 Change two errors to warnings
- [ ] Migrate #1037 (448f1ca33)
- 2534b8000 Handling incomplete traces.
- [ ] Migrate #1018 (eeac67231)
- 092f8e224 Lazy methods: fault in static initializer if a static method is called
- [ ] Migrate #1044 (e6e7e168f)
- 471254ce3 Fix win32 compilation
- [ ] Migrate #1045 (8cf48d329)
- ce8303968 Replace std::cout for errors with messaget::error()
- [ ] Migrate #1047 (cf0875a9e)
- 53237027b Fix bad return type of char pointer func
- [ ] Migrate #1048 (f84d96b11)
- 1e567fbe4 Add an add_axioms_for_concat_substr function
- 334ab00b9 Comment in description of test for String.replace()
- ef5bd4dbf Modifications to doxygen
- cf39c2994 Replace asserts
- [ ] Migrate #1001 (a9de8594a)
- 02b794290 Simplifying expressions of the form &array[0] in json
- f4fa77802 Simplifying array access and expressions with pointer offsets
- 5cfa41309 Adding test to check that data field of strings are set in json
- f950ffc74 Documentation for json_goto_trace in doxygen format
- [ ] Migrate #922 (05875e1d7)
- fbb5724db Declaring string expression symbol for each string_exprt
- 50be5302d Removing overflow check in quantified formula
- [ ] Migrate #1021 (70a980660)
- c745aa79d Improvements in the code for String.toCharArray in preprocessing
- 0619f0587 Better test for String.toCharArray
- [ ] Migrate #1026 (fbe8be8dd)
- bc968b0f7 Always pass namespace to from_expr
- [ ] Migrate #1051 (9ac5dff9d)
- b0b21bbb5 Remove functions that are destined to be modelled in Java
- a95e8dc33 Removing comments on non-supported functions in string preprocessing
- fdb6f2e5c Ordering functions in alphabetic order in initialize conversion table
- [ ] Migrate #992 (0610b0d74)
- 6a156a9f6 Making toLowerCase more precise
- 5553652ef Improving the test for Java case functions
- 695b3ce4a Add comments about characters transformed by toLowerCase
- [ ] Migrate #1036 (71ace4332)
- 0e5b254cf Java frontend: Set source locations on instructions in code_blocks
- [ ] Migrate #1055 (d68f1372e)
- 33fc907df Call remove-skip before coverage instrumentation
- [ ] Migrate #1056 (7583da2a0)
- 20e4def6a Add preformatted message flag
- [ ] Migrate #1059 (406a6c40e)
- 913de981b check for java bytecode index in the existing coverage
- a63f2bbd0 replaced assertion by invariant in cover.cpp
- [ ] Migrate #772 (71b3fd2d1)
- 6b6f6cb45 Add message for unknown cbmc option
- [ ] Migrate #910 (f690a3c80)
- edd7b0a5d Fix remove_pointer_offsets
- [ ] Migrate #1066 (a85737244)
- fde9c7659 Correcting assertions.
- [ ] Migrate #990 (77bda4efc)
- 9bb474dc0 Fixes parameter detection on bytecode->goto translation
- 0968e9368 Regression tests: java method parameter detection
- 1e68ad273 Documentation: functionality around `setup_local_variables`
- [ ] Migrate #1053 (6c0fcda90)
- 70d0cb0e0 Forgotten premise in add_axioms_from_int
- 8a803100e Correcting when to do overflow check in add_axioms_from_int
- 15e88e736 Making tests for int to string conversion more precise
- 7fa229b3d Update comments in add_axioms_from_int to reflect changes in the code
- fb3ab81c0 Using PRECONDITION instead of assert
- eaad10007 Comment on the bound for overflow in int to string conversion
- 4440343e1 Adding tests for String.valueOf(long)
- 20f395172 Correction of line numbers in valueOf(long) test
- [ ] Migrate #1033 (4a2876baf)
- 9c94cb30b Correcting initialization of floatbv_typecast_exprt
- d8af6b648 Adding id for scientific notation of floats
- 5f28dc66d New file for conversion between floats and strings
- 518efa497 Conversion between string and float moved into a new file
- 685a105e2 Improving the float to string conversion in the preprocessing
- 4ecec1ab1 Improve the documentation of the string preprocessing
- 8367ff522 Allocate array in String result of String.valueOf(F)
- 651836996 Adding test for the String.valueOf(F) function
- 5c71733f9 Comment corrections in string_constraint_generator_concat
- a8b1e8ec6 Changing assert for PRECONDITION and UNREACHABLE in float to string conversion
- 105925ac4 Comment corrections in string_constraint_generator_float
- 4eacbd359 Renaming add_axioms_from_float to add_axioms_for_string_of_float
- cae6d279b Style improvements in string_constraint_generator_float.cpp
- 64558ca16 Update comments in string_constraint_generator_valueof.cpp
- e1f2d77fa Adding tests for String.valueOf float
- [ ] Migrate #1017 (d32543190)
- d299ea29e Allow "unknown" value assignments in JSON trace
- 82642b959 Add regression test for nil assigns in JSON trace
- [ ] Migrate #1050 (56307d03c)
- af4edae93 Fixing inheritance issue for java programs.
- [ ] Migrate #1064 (b63547fbc)
- 0e4176d23 Fix modes in java entry point code
- 5409f5631 Add missing header guard endif comment
- [ ] Migrate #1079 (6a18c24aa)
- cf2600829 Discard LVT if bytecode > codet translation cannot make sense of it
- 5330536f5 Documentation for java_bytecode_convert_methodt::variable
- a1af44f10 Regression tests: groovyc lvts
- [ ] Migrate #1067 (2a7e25c7d)
- 50732ee85 Create is_digit_with_radix()
- 4e5d8cce4 add_axioms_for_parse_int can take optional radix
- 238c02fa8 Add parseInt with radix to preprocessing
- [ ] Migrate #1077 (3d418796b)
- 72677f2b6 Add regression test for runtime exceptions instrumentation
- 961c0a35f Refactoring the runtime exception instrumentation out of java_bytecode_convert
- a6d1084e3 Move generate_class_stub out of java_bytecode_convert_classt and to java_utils.cpp and use it to generate stubs for exceptions
- 236e44231 Adjusted runtime exceptions regression tests
- [ ] Migrate #1019 (8226c5b7e)
- 87ff9de34 Fixed function inversion.
- cd29f689d Extended check_axioms for not_contains and refactored
- 05516bbf5 Added regresion test for indexOf
- [ ] Migrate #1071 (7c415e89f)
- f5f122e55 Added lower bound in lastIndexOf
- bb31bb547 Added regression test for lastIndexOf
- [ ] Migrate #1076 (c242674b9)
- 8495451a9 For contains, added bounds for substring index in !contains case
- 939fb8766 Added regression tests based on originating test-gen tests
- [ ] Migrate #1078 (530a2dd62)
- ca3dbab05 check_class_cast: don't duplicate existing assertion
- 73bd18d6a Don't throw ClassCastException when casting null pointer
- [ ] Migrate #1098 (a3e75574a)
- eb3b64c93 Ensure source locations are assigned to all expressions
- [ ] Migrate #1088 (6c7d6d49e)
- 41bb0d443 Store in the class_typet whether the class is abstract
- 4193022c8 Added unit tests to demonstrate the abstract flag
- [ ] Migrate #1084 (941945491)
- 280c45b13 Declare malloc-site symbol before use
- 8082795f4 Add test checking that string content is declared before being allocated
- [ ] Migrate #1103 (836be74b8)
- 07ff02d22 Removing string literal function from string preprocess cpp
- c33306a9d Removing string_literal declaration
- [ ] Migrate #1102 (f8131c35e)
- e2dea9b4f Correcting type in add axiom for int
- [ ] Migrate #1106 (79c0aaaf0)
- 735065ce9 Make Long.parseLong work
- [ ] Migrate #1097 (a64e6ed9c)
- bb108a3d5 Call `get_language_options` on `--show-parse-tree`
- [ ] Migrate #1113 (98488bf6b)
- 8dcff58e8 Code tidy changes
- a904f089c Add class for randomly selecting a concrete child of an abstract class
- d5513db13 Make class derived from object factory
- 78a4e05ad Made the random selection alphabetical instead of random
- 2c79f51fb Removed extra code and just combined into gen_nondet_pointer_init
- e4ac6e21f Modified definition of abstract to not fall over on void* types
- 90286a86f Adding regression tests showing the modified gen code works
- 248ec8ea3 Don't require pointers point to classes
- a3f7eedfd Made jsonArrays test less strict
- e2e670efa Removing whitespace that causes an error on windows
- [ ] Migrate #1100 (da1dc29d2)
- d0d046aa5 Add call-graph inversion function
- [ ] Migrate #1112 (db0b1f298)
- 728bbc383 Consider implicit exceptions when building the CFG from bytecode
- 68f6ccd42 Adjust regression tests for exceptions: given that we now consider implicit exceptions when building the CFG, there is no need for the redundant explicit throws
- 85b2a6d82 Added two more tests for runtime exceptions
- [ ] Migrate #1096 (2c29180fc)

**Comment by tautschnig** [comment]
There is now https://github.com/diffblue/cbmc/tree/rebased-test-gen-support that has all commits in test-gen-support up to e8e20ea4fe0, rebased onto current master (d63d2c7a). @peterschrammel has more details.

**Comment by tautschnig** [comment]
FWIW, I have rebased https://github.com/diffblue/cbmc/tree/rebased-test-gen-support to account for #890. Hopefully that one was the last of the across-the-code-base changes.

**Comment by tautschnig** [comment]
This plan seems to have been shelved. We'll release from develop.
